### ISSUE TITLE
本地测试几个环境都出现了图中问题

### ISSUE THREAD

**Issue by SummerSec** [bigBestWay/ice#2]
应该是读取`/proc/self/mem `出现的问题，没有获取到**native_jvmtienv**。

![image](https://user-images.githubusercontent.com/47944478/159147242-0c4b85f2-3d87-41e7-a1bb-d1dfcd345866.png)

**Comment by SummerSec** [comment]
还有一个问题就是Lang.BYTES是jdk8才有的，建议替换成 **int i=8**即可，否则在jdk6/7编译失败。
![image](https://user-images.githubusercontent.com/47944478/159147728-6136a0ca-2ad8-42aa-9081-549634912a84.png)

![image](https://user-images.githubusercontent.com/47944478/159147760-642d9a31-0257-48a1-ad4f-e572326db41d.png)

https://github.com/bigBestWay/ice/pull/3

**Comment by SummerSec** [comment]
[hs_err_pid5818.log](https://github.com/bigBestWay/ice/files/8310596/hs_err_pid5818.log)
 
这个是错误日志信息。

**Comment by SummerSec** [comment]
测试openjdk也会有这个问题。
![image](https://user-images.githubusercontent.com/47944478/159147962-eca8b09c-2751-4279-9a3d-6ea9fba6f1ef.png)

**Comment by SummerSec** [comment]
能发现问题出现在
RandomAccessFile的length方法上

![image](https://user-images.githubusercontent.com/47944478/159165801-cfa501a6-d4cc-423d-b8d2-4a2310d00dc1.png)

**Comment by cnblogqaq** [comment]
> 应该是读取`/proc/self/mem `出现的问题，没有获取到**native_jvmtienv**。
> 
> ![image](https://user-images.githubusercontent.com/47944478/159147242-0c4b85f2-3d87-41e7-a1bb-d1dfcd345866.png)

我测试也出了这个问题，请问师傅你解决了吗？

**Comment by SummerSec** [comment]
> > 应该是读取`/proc/self/mem `出现的问题，没有获取到**native_jvmtienv**。
> > 
> > ![image](https://user-images.githubusercontent.com/47944478/159147242-0c4b85f2-3d87-41e7-a1bb-d1dfcd345866.png)
> 
> 我测试也出了这个问题，请问师傅你解决了吗？

没有

**Comment by bigBestWay** [comment]
这个可能需要使用gdb等汇编级调试工具进行调试了

**Comment by bigBestWay** [comment]
已解决
https://github.com/bigBestWay/ice/commit/009cbc461b6e027db467ca0cb31f29e16e4391cb
